### ISSUE TITLE
Error after python update 3.9.1

### ISSUE THREAD

**Issue by andrearomanoif** [Ligio/hacc-ozmo#16]
I am using last version of home assistant 2021.2.1 and python 3.9.1.
After update I have this error with deebot 900 model DE5G:

2021-02-07 16:32:44 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up deebot platform for vacuum
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/deebot/vacuum.py", line 28, in setup_platform
    vacuums.append(EcovacsDeebotVacuum(device, hass.data[ECOVACS_CONFIG][0]))
  File "/home/homeassistant/.homeassistant/custom_components/deebot/vacuum.py", line 41, in __init__
    self.device.connect_and_wait_until_ready()
  File "/srv/homeassistant/lib/python3.9/site-packages/ozmo/__init__.py", line 456, in connect_and_wait_until_ready
    self.iotmq.schedule(30, self.send_ping)
  File "/srv/homeassistant/lib/python3.9/site-packages/ozmo/__init__.py", line 750, in schedule
    if not self.scheduler_thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'
2021-02-07 16:32:44 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2021-02-07 16:32:44 WARNING (MainThread) [homeassistant.config_entries] Config entry 'HP30E171DBD4F1' for ipp integration not ready yet. Retrying in 5 seconds
/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/cast/media_player.py:136: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
  done, _ = await asyncio.wait(

You have a solution?

**Comment by MajorBreakfast** [comment]
The `isAlive` issue is now fixed https://github.com/Ligio/hacc-ozmo/issues/24
