### ISSUE TITLE
Deebot 930 Not Working

### ISSUE THREAD

**Issue by bossben8** [Ligio/hacc-ozmo#25]
ERROR (MainThread) [homeassistant.setup] Error during setup of component deebot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 248, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deebot/__init__.py", line 64, in setup
    device["nick"],
KeyError: 'nick'

**Comment by JartX** [comment]
Same problem here

**Comment by mannipulator** [comment]
I had the same error. In my case the device["nick"] call in the logger caused the failure. I just removed those 4 lines and now its working fine.

`    
for device in devices:

        # _LOGGER.info(
            # "Discovered Ecovacs device on account: %s with nickname %s",
            # device["did"],
            # device["nick"],
        # )
        vacbot = VacBot(
            ecovacs_api.uid,
            ecovacs_api.REALM,
            ecovacs_api.resource,
            ecovacs_api.user_access_token,
            device,
            config[DOMAIN].get(CONF_CONTINENT).lower(),
            monitor=True,
        )`
