### ISSUE TITLE
Exception on startup with OZMO Slim10

### ISSUE THREAD

**Issue by AfonsoFGarcia** [Ligio/hacc-ozmo#47]
Whenever starting up with a Deebot OZMO Slim10, I get this error:

```
2023-08-21 16:29:21.365 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up deebot platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deebot/vacuum.py", line 46, in setup_platform
    vacuums.append(EcovacsDeebotVacuum(device, hass.data[ECOVACS_CONFIG][0]))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deebot/vacuum.py", line 59, in __init__
    self.device.connect_and_wait_until_ready()
  File "/usr/local/lib/python3.11/site-packages/ozmo/__init__.py", line 461, in connect_and_wait_until_ready
    self.send_ping()
  File "/usr/local/lib/python3.11/site-packages/ozmo/__init__.py", line 628, in send_ping
    self.request_all_statuses()
  File "/usr/local/lib/python3.11/site-packages/ozmo/__init__.py", line 662, in request_all_statuses
    self.refresh_statuses()
  File "/usr/local/lib/python3.11/site-packages/ozmo/__init__.py", line 647, in refresh_statuses
    self.run(GetCleanState())
  File "/usr/local/lib/python3.11/site-packages/ozmo/__init__.py", line 673, in run
    self.send_command(action)
  File "/usr/local/lib/python3.11/site-packages/ozmo/__init__.py", line 670, in send_command
    self.iotmq.send_command(action, self._vacuum_address())  #IOTMQ devices need the full action for additional parsing
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ozmo/__init__.py", line 789, in send_command
    self._handle_ctl_api(
  File "/usr/local/lib/python3.11/site-packages/ozmo/__init__.py", line 871, in _handle_ctl_api
    s(resp)
  File "/usr/local/lib/python3.11/site-packages/ozmo/__init__.py", line 470, in _handle_ctl
    getattr(self, method)(ctl)
  File "/usr/local/lib/python3.11/site-packages/ozmo/__init__.py", line 500, in _handle_clean_report
    type = event['type']
           ~~~~~^^^^^^^^
KeyError: 'type'
```

Any idea on what is wrong? Country `pt` and continent `eu` set in the config.

**Comment by AfonsoFGarcia** [comment]
Found the issue! The vacuum doesn't return the clean report type unless it's cleaning. Created this PR in the ozmo library to fix it: https://github.com/Ligio/ozmo/pull/16
