### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by Salsalove** [Ligio/hacc-ozmo#51]
With 2024.12.2 the custom component doesn't work anymore. I try to delete and reinstall it but I have this error:

![image](https://github.com/user-attachments/assets/8c154103-bbbd-42c3-8ddd-dc781cb3c8e1)

**Comment by derk1983** [comment]
For me also:

```
The logs:

SUPPORT_STOP was used from deebot, this is a deprecated constant which will be removed in HA Core 2025.10. Use VacuumEntityFeature.STOP instead, please report it to the author of the 'deebot' custom integration
SUPPORT_TURN_OFF was used from deebot, this is a deprecated constant which will be removed in HA Core 2025.10. Use VacuumEntityFeature.TURN_OFF instead, please report it to the author of the 'deebot' custom integration
SUPPORT_TURN_ON was used from deebot, this is a deprecated constant which will be removed in HA Core 2025.10. Use VacuumEntityFeature.TURN_ON instead, please report it to the author of the 'deebot' custom integration
SUPPORT_START was used from deebot, this is a deprecated constant which will be removed in HA Core 2025.10. Use VacuumEntityFeature.START instead, please report it to the author of the 'deebot' custom integration
SUPPORT_PAUSE was used from deebot, this is a deprecated constant which will be removed in HA Core 2025.10. Use VacuumEntityFeature.PAUSE instead, please report it to the author of the 'deebot' custom integration
```

**Comment by Salsalove** [comment]
@Ligio can you help us?

**Comment by brooksben11** [comment]
I believe the issue is actually between 12.2 and 12.3 (It only errored out for me when upgrading from 12.2 to 12.3). Relevant bit in the logs:

`2024-12-13 09:58:06.409 ERROR (MainThread) [homeassistant.setup] Error during setup of component deebot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deebot/__init__.py", line 92, in setup
    ecovacs_api = EcoVacsAPI(
        ECOVACS_API_DEVICEID,
    ...<3 lines>...
        config[DOMAIN].get(CONF_CONTINENT),
    )
  File "/usr/local/lib/python3.13/site-packages/ozmo/__init__.py", line 194, in __init__
    login_info = self.__call_main_api('user/login',
                                      ('account', self.encrypt(account_id)),
                                      ('password', self.encrypt(password_hash)))
  File "/usr/local/lib/python3.13/site-packages/ozmo/__init__.py", line 238, in __call_main_api
    raise RuntimeError("failure code {} ({}) for call {} and parameters {}".format(
        json['code'], json['msg'], function, args))
RuntimeError: failure code 0001 (操作失败) for call user/login and parameters`


I removed some things from the very end which I think may be account specific identifiers?

**Comment by Salsalove** [comment]
But, I deleted the custom integration and now I can't reinstall it again from HACS...

@brooksben11  maybe you upgraded from 12.1 to 12.2 (12.3 in still in beta?)

**Comment by brooksben11** [comment]
> But, I deleted the custom integration and now I can't reinstall it again from HACS...
> 
> @brooksben11 maybe you upgraded from 12.1 to 12.2 (12.3 in still in beta?)

12.3 dropped today.
https://www.home-assistant.io/blog/2024/12/04/release-202412/#2024123---december-13

I only had issues after I upgraded. I'd been on 12.2 since it came out a few days ago.

**Comment by Salsalove** [comment]
> > But, I deleted the custom integration and now I can't reinstall it again from HACS...
> > @brooksben11 maybe you upgraded from 12.1 to 12.2 (12.3 in still in beta?)
> 
> 12.3 dropped today. https://www.home-assistant.io/blog/2024/12/04/release-202412/#2024123---december-13
> 
> I only had issues after I upgraded. I'd been on 12.2 since it came out a few days ago.

I have 12.2, so for me the problem isn't the last HA upgrade. I think something about HACS, otherwise it is not explained why I can't reinstall it

**Comment by brooksben11** [comment]
> > > But, I deleted the custom integration and now I can't reinstall it again from HACS...
> > > @brooksben11 maybe you upgraded from 12.1 to 12.2 (12.3 in still in beta?)
> > 
> > 
> > 12.3 dropped today. https://www.home-assistant.io/blog/2024/12/04/release-202412/#2024123---december-13
> > I only had issues after I upgraded. I'd been on 12.2 since it came out a few days ago.
> 
> I have 12.2, so for me the problem isn't the last HA upgrade. I think something about HACS, otherwise it is not explained why I can't reinstall it

That makes me think it's not a HA issue, but rather a Deebot server issue (and why it just started for me because it reloaded the integration after the upgrade/restart). That might also explain why you can't reinstall it, if it can't set it up at all.

Hopefully it's just a temporary issue. I literally was just using it prior to my upgrade.

**Comment by Salsalove** [comment]
> That makes me think it's not a HA issue, but rather a Deebot server issue (and why it just started for me because it reloaded the integration after the upgrade/restart). That might also explain why you can't reinstall it, if it can't set it up at all.

Nope...i can't reinstall the custom component from zero, and it can't depend from deebot server issues (they could cause connection problems with the devices but not the installation of the component on HACS)...I think there is a problem between HACS version and the custom integration.

**Comment by nanomad** [comment]
> But, I deleted the custom integration and now I can't reinstall it again from HACS...
> 
> @brooksben11 maybe you upgraded from 12.1 to 12.2 (12.3 in still in beta?)

This is due to a missing hacs manifest file, I've fixed it in my fork if you want to try (altough ecovacs login seems broken at the moment)

**Comment by TwoB33RS** [comment]
Hi, i did not updated to 24.12.x until today (was running 11.3 , after my deebot 901 stopped working some days ago (may two days before 🤷) Our old devices are not supported by the core integration (at the moment, some one has to provide api doc for this models). I also updated HACS and this integration today (after stopped working)

I have the feeling that our outage is not depending on the HA core Update / Version. The timing matches, so maybe really "just" an login issue. I still hoping for an fix 🙏 so if we can provide any information or support to get this back running, let know.

**Comment by nanomad** [comment]
@TwoB33RS  indeed looks like ecovacs is rejecting the old login method while the new one used by "HA" client works just fine. 

I'll see if I can work on adding missing XML commands support to the official client

**Comment by 32Dexter** [comment]
> @TwoB33RS indeed looks like ecovacs is rejecting the old login method while the new one used by "HA" client works just fine.
> 
> I'll see if I can work on adding missing XML commands support to the official client

Sorry to butt in, I also use this integration for the Deebot 605. It doesn't seem like a login error to me, or rather, you get a login error because the API site is under maintenance (ecouser.net), correct?

**Comment by TwoB33RS** [comment]
I was very happy about this integration, but maybe is some able to create the needed .py file for the official integration. I think our 900er work very similar and one for all will nearly fix them all.

Im not very familiar with api revers engineering by proxy traffic analysing.

**Comment by derk1983** [comment]
I'm running Homeassistant beta 2025.1.0b2. The Ecovacs integration is working again.

**Comment by Salsalove** [comment]
Yes, now it's working again

**Comment by TwoB33RS** [comment]
sounds like a late Chrismas gift, but i can say that its not depending on 25.1, because iam still on 24.12.5 and just (after reading your comments) readding yaml entries for deebot config and it working again. So it seems that the "old" connect method was reactivated by ecovacs or thing 🤷 or have someone more information?
In my case it got broke with out any changes, and fixed with out (yaml reconfig dont count) any changes / updates.

anyway many thanks to the developer of this integration for our old and lovely underrated deebot :-)
